# Kept in sync with the xl-release repository's gradle.properties: this project is consumed by
# xl-release (com.xebialabs.deployit.gradle:license-data, pinned there as licenseDatabaseVersion),
# so the build toolchain and the xebialabs plugin versions deliberately track that repo.
# javaLanguageVersion is used by toolchain
javaLanguageVersion=21
languageLevel=21
xlDefaultsPluginVersion=4.0.5
xlDependencyPluginVersion=6.0.0
